//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projent_NOTZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBook
    {
        public int Order_Id { get; set; }
        public Nullable<int> Order_SalesId { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Order_NumProduct { get; set; }
        public Nullable<int> Order_BookId { get; set; }
        public Nullable<decimal> Order_Price { get; set; }
        public Nullable<int> Order_Status_Id { get; set; }
    
        public virtual ProductBook ProductBook { get; set; }
        public virtual SalesSlip SalesSlip { get; set; }
        public virtual Status Status { get; set; }
    }
}
