//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projent_NOTZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Pay_Id { get; set; }
        public Nullable<int> Pay_Oder_Id { get; set; }
        public Nullable<int> Pay_Product_Id { get; set; }
        public byte[] Pay_Slipimage { get; set; }
    }
}
