//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projent_NOTZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesSlip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesSlip()
        {
            this.OrderBook = new HashSet<OrderBook>();
        }
    
        public int Sales_Id { get; set; }
        public string Sales_date { get; set; }
        public Nullable<int> Sales_Product { get; set; }
        public Nullable<int> Sales_Userid { get; set; }
        public Nullable<int> Sales_NumProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBook { get; set; }
        public virtual User User { get; set; }
    }
}
